"""Generate the winget manifest set for one release.

The winget community repository stores manifests, never installers, so every
release needs its own three YAML files carrying the installer URL and its
SHA-256. Producing them in the release job means the hash is the real one rather
than something copied by hand.

Usage::

    python tools/make_winget_manifest.py \
        --installer Output/Setup-StreamLabsTikTokStreamKeyGenerator-2.2.0.exe \
        --version 2.2.0 \
        --output winget-out

The result is laid out the way the pull request has to be: the first letter of
the identifier in lower case, then every segment of the identifier.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

REPOSITORY = "tacosandtypescript-debug/StreamLabsTikTokStreamKeyGenerator"
PACKAGE_IDENTIFIER = "tacosandtypescript-debug.StreamLabsTikTokStreamKeyGenerator"
PACKAGE_NAME = "StreamLabsTikTokStreamKeyGenerator"
PUBLISHER = "tacosandtypescript-debug"
PUBLISHER_URL = "https://github.com/tacosandtypescript-debug"
LICENSE = "GPL-3.0-or-later"
LICENSE_URL = f"https://github.com/{REPOSITORY}/blob/main/LICENSE.txt"
SHORT_DESCRIPTION = (
    "Desktop application that prepares a TikTok LIVE RTMP session through Streamlabs."
)
MONIKER = "streamlabs-keygen"
TAGS = ("obs-studio", "streaming", "tiktok", "stream-key")
# The version the winget-pkgs pull request template still asks for.
MANIFEST_VERSION = "1.12.0"
DEFAULT_LOCALE = "en-US"
MINIMUM_OS_VERSION = "10.0.17763.0"
SCHEMA_PREFIX = "https://aka.ms/winget-manifest"

REQUIRED_NOTES = """\
These manifests were generated by the release workflow. Read winget/README.md
before opening the pull request: it lists the two checks that decide whether the
package is accepted, and the identifier question that is worth deciding first.
"""


def sha256_of(path: Path) -> str:
    """Return the upper-case SHA-256 of a file, as winget writes it."""

    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest().upper()


def manifest_directory(version: str, root: Path) -> Path:
    """Return the folder winget expects for this package and version."""

    return (
        Path(root)
        / "manifests"
        / PACKAGE_IDENTIFIER[0].lower()
        / PUBLISHER
        / PACKAGE_NAME
        / version
    )


def installer_url(version: str, installer_name: str) -> str:
    """Return the public download URL of the installer of ``version``."""

    return f"https://github.com/{REPOSITORY}/releases/download/v{version}/{installer_name}"


def version_manifest(version: str) -> str:
    return (
        f"# yaml-language-server: $schema={SCHEMA_PREFIX}.version.{MANIFEST_VERSION}.schema.json\n"
        f"PackageIdentifier: {PACKAGE_IDENTIFIER}\n"
        f"PackageVersion: {version}\n"
        f"DefaultLocale: {DEFAULT_LOCALE}\n"
        "ManifestType: version\n"
        f"ManifestVersion: {MANIFEST_VERSION}\n"
    )


def locale_manifest(version: str) -> str:
    tags = "".join(f"  - {tag}\n" for tag in TAGS)
    return (
        f"# yaml-language-server: $schema={SCHEMA_PREFIX}.defaultLocale."
        f"{MANIFEST_VERSION}.schema.json\n"
        f"PackageIdentifier: {PACKAGE_IDENTIFIER}\n"
        f"PackageVersion: {version}\n"
        f"PackageLocale: {DEFAULT_LOCALE}\n"
        f"Publisher: {PUBLISHER}\n"
        f"PublisherUrl: {PUBLISHER_URL}\n"
        f"PackageName: {PACKAGE_NAME}\n"
        f"PackageUrl: https://github.com/{REPOSITORY}\n"
        f"License: {LICENSE}\n"
        f"LicenseUrl: {LICENSE_URL}\n"
        f"ShortDescription: {SHORT_DESCRIPTION}\n"
        f"Moniker: {MONIKER}\n"
        "Tags:\n"
        f"{tags}"
        f"ReleaseNotesUrl: https://github.com/{REPOSITORY}/releases\n"
        "ManifestType: defaultLocale\n"
        f"ManifestVersion: {MANIFEST_VERSION}\n"
    )


def installer_manifest(version: str, url: str, digest: str) -> str:
    return (
        f"# yaml-language-server: $schema={SCHEMA_PREFIX}.installer."
        f"{MANIFEST_VERSION}.schema.json\n"
        f"PackageIdentifier: {PACKAGE_IDENTIFIER}\n"
        f"PackageVersion: {version}\n"
        f"InstallerLocale: {DEFAULT_LOCALE}\n"
        "Platform:\n"
        "  - Windows.Desktop\n"
        f"MinimumOSVersion: {MINIMUM_OS_VERSION}\n"
        "InstallerType: inno\n"
        "Scope: user\n"
        "InstallModes:\n"
        "  - interactive\n"
        "  - silent\n"
        "  - silentWithProgress\n"
        "UpgradeBehavior: install\n"
        "Installers:\n"
        "  - Architecture: x64\n"
        f"    InstallerUrl: {url}\n"
        f"    InstallerSha256: {digest}\n"
        "    AppsAndFeaturesEntries:\n"
        f"      - DisplayName: {PACKAGE_NAME}\n"
        f"        Publisher: {PUBLISHER}\n"
        "        InstallerType: inno\n"
        "ManifestType: installer\n"
        f"ManifestVersion: {MANIFEST_VERSION}\n"
    )


def write_manifests(
    installer: Path,
    version: str,
    output: Path,
) -> list[Path]:
    """Write the three manifests of a release and return their paths."""

    installer = Path(installer)
    if not installer.is_file():
        raise FileNotFoundError(f"No existe el instalador: {installer}")

    directory = manifest_directory(version, Path(output))
    directory.mkdir(parents=True, exist_ok=True)
    digest = sha256_of(installer)
    url = installer_url(version, installer.name)

    files = {
        f"{PACKAGE_IDENTIFIER}.yaml": version_manifest(version),
        f"{PACKAGE_IDENTIFIER}.locale.{DEFAULT_LOCALE}.yaml": locale_manifest(version),
        f"{PACKAGE_IDENTIFIER}.installer.yaml": installer_manifest(version, url, digest),
    }

    written: list[Path] = []
    for name, body in files.items():
        path = directory / name
        path.write_text(body, encoding="utf-8")
        written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--installer", required=True, type=Path)
    parser.add_argument("--version", required=True)
    parser.add_argument("--output", required=True, type=Path)
    arguments = parser.parse_args(argv)

    try:
        written = write_manifests(arguments.installer, arguments.version, arguments.output)
    except (OSError, ValueError) as exc:
        print(f"No se pudieron generar los manifiestos: {exc}", file=sys.stderr)
        return 1

    for path in written:
        print(path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
